import { useEffect, useState } from "react";


export default function App() {

  const [loading, setLoading] = useState(0);


    useEffect(() => {

        let value = 0;

            const timer = setInterval(() => {

                  value += 2;

                        setLoading(value);

                              if (value >= 100) {
                                      clearInterval(timer);
                                            }

                                                }, 40);


                                                    return () => clearInterval(timer);

                                                      }, []);



                                                        return (

                                                            <div
                                                                  dir="rtl"
                                                                        className="
                                                                              min-h-screen
                                                                                    bg-[#0b0b0a]
                                                                                          flex
                                                                                                items-center
                                                                                                      justify-center
                                                                                                            text-white
                                                                                                                  relative
                                                                                                                        overflow-hidden
                                                                                                                              "
                                                                                                                                  >


                                                                                                                                        {/* خلفية الشبكة */}

                                                                                                                                              <div
                                                                                                                                                      className="
                                                                                                                                                              absolute
                                                                                                                                                                      inset-0
                                                                                                                                                                              opacity-20
                                                                                                                                                                                      bg-[linear-gradient(#555_1px,transparent_1px),linear-gradient(90deg,#555_1px,transparent_1px)]
                                                                                                                                                                                              bg-[size:45px_45px]
                                                                                                                                                                                                      "
                                                                                                                                                                                                            />


                                                                                                                                                                                                                  {/* المحتوى */}

                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                className="
                                                                                                                                                                                                                                        relative
                                                                                                                                                                                                                                                flex
                                                                                                                                                                                                                                                        flex-col
                                                                                                                                                                                                                                                                items-center
                                                                                                                                                                                                                                                                        "
                                                                                                                                                                                                                                                                              >


                                                                                                                                                                                                                                                                                      {/* الغراب */}

                                                                                                                                                                                                                                                                                              <img

                                                                                                                                                                                                                                                                                                        src="/raven.png"

                                                                                                                                                                                                                                                                                                                  alt="ANZU Raven"

                                                                                                                                                                                                                                                                                                                            className="
                                                                                                                                                                                                                                                                                                                                      w-64
                                                                                                                                                                                                                                                                                                                                                h-64
                                                                                                                                                                                                                                                                                                                                                          object-contain
                                                                                                                                                                                                                                                                                                                                                                    drop-shadow-[0_0_30px_rgba(255,255,255,0.25)]
                                                                                                                                                                                                                                                                                                                                                                              "

                                                                                                                                                                                                                                                                                                                                                                                      />



                                                                                                                                                                                                                                                                                                                                                                                              {/* الاسم */}

                                                                                                                                                                                                                                                                                                                                                                                                      <h1
                                                                                                                                                                                                                                                                                                                                                                                                                className="
                                                                                                                                                                                                                                                                                                                                                                                                                          mt-5
                                                                                                                                                                                                                                                                                                                                                                                                                                    text-5xl
                                                                                                                                                                                                                                                                                                                                                                                                                                              tracking-[0.7em]
                                                                                                                                                                                                                                                                                                                                                                                                                                                        text-[#c58b55]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  font-serif
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              A . N . Z . U

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </h1>



                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* الوصف */}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          mt-6
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    text-xl
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              text-gray-400
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          مساعدك الشخصي

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>




                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* شريط التحميل */}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      mt-14
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                w-72
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          h-[3px]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    bg-gray-700
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              overflow-hidden
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  h-full
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              bg-[#c58b55]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          transition-all
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                width:`${loading}%`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>




                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* زر الدخول */}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  mt-12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            px-12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      py-3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rounded-xl
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border-[#c58b55]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              text-[#c58b55]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        hover:bg-[#c58b55]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  hover:text-black
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            transition
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        دخول

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>



                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* الإصدار */}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  absolute
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          bottom-5
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  left-6
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          text-gray-600
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                v0.1

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }